refactor: use JsonUnit instead of JSONAssert
JsonUnit provides nicer integration with AssertJ, doesn't have the
dependency issue[1] JSONAssert has, is maintained (JSONAssert doesn't
seem to be) and generates much nicer failure messages:

```
Different value found in node "spreadsheetId", expected: <"6364c6b9-ea7f-4caf-916b-3baeb6622c24x"> but was: <"6364c6b9-ea7f-4caf-916b-3baeb6622c24">.
```
or
```
Different keys found in node "", extra: "ID","SerialNumbers","Specification", expected: <{"Description":"New Monitor with Resolution 1920 x 1080 @ 60Hz","Name":"NEC Screen"}> but was: <{"Description":"New Monitor with Resolution 1920 x 1080 @ 60Hz","ID":4,"Name":"NEC Screen","SerialNumbers":[],"Specification":""}>

```

[1] https://github.com/skyscreamer/JSONassert/issues/99