fix: flaky Events integration test
Any number of events could have been fired, so instead of looking at the
first recorded event invocation, we should consider all. Looking
specifically at the first element leads to:

```
[INFO] Running io.syndesis.server.runtime.EventsITCase
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.653 s <<< FAILURE! - in io.syndesis.server.runtime.EventsITCase
Error:  io.syndesis.server.runtime.EventsITCase.wsEventsWithToken  Time elapsed: 0.259 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:

Expecting:
 <"{"event":"change-event","data":"{\"action\":\"updated\",\"kind\":\"integration-bulletin-board\",\"id\":\"i-MtsE0ef35Cg9gwTr0uoz\"}"}">
to be equal to:
 <"{"event":"change-event","data":"{\"action\":\"created\",\"kind\":\"integration\",\"id\":\"1002\"}"}">
but was not.
	at io.syndesis.server.runtime.EventsITCase.wsEventsWithToken(EventsITCase.java:192)
```