fix(build): support very old git version
The version of Git we have on Fabric8 Jenkins nodes doesn't support
sorting in `git tag`. This uses `git for-each-ref` instead.

Solves this issue on the release build:

```
error: unknown option `sort=taggerdate'
```

(cherry picked from commit c2e43e28fc1eed24eaf70781e1c843949df63a7a)