fix: revert `google-api-services-gmail` upgrade
This reverts the upgrade of `com.google.apis:google-api-services-gmail`
which was causing a runtime exception at the integration startup:

```
Caused by: java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
    at com.google.api.services.gmail.Gmail$Builder.setBatchPath (Gmail.java:9868)
    at com.google.api.services.gmail.Gmail$Builder.<init> (Gmail.java:9847)
```

Also adds a integration test that only checks if the integration can be
started, as we have no way of stubbing the www.googleapis.com endpoint
that will be contacted otherwise.