fix(operator): issues caused by version upgrades 3
This upgrades controller-runtime to fix the following compile issue:

```
vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go:134:3: cannot use &latencyAdapter{...} (type *latencyAdapter) as type metrics.LatencyMetric in field value:
	*latencyAdapter does not implement metrics.LatencyMetric (wrong type for Observe method)
		have Observe(string, url.URL, time.Duration)
		want Observe(context.Context, string, url.URL, time.Duration)
vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go:135:3: cannot use &resultAdapter{...} (type *resultAdapter) as type metrics.ResultMetric in field value:
	*resultAdapter does not implement metrics.ResultMetric (wrong type for Increment method)
		have Increment(string, string, string)
		want Increment(context.Context, string, string, string)
```