chore(deps): upgrade to microbundle 0.13.3
Few packages that used an older microbundle version (0.11.0), which
depends on brotli-size (0.0.3) that in turn depends on iltorb which has
been archived for a bit over a year now.

In addition to changing the microbundle dependency to 0.13.3 I had to
change the TypeScript compiler configuration not to include `../.jest/`,
as that seems to result in generating paths in `dist` for `.ts.d` files
that do not match the compiled `.js` files. Which lead to errors like:

```
Failed to compile.

app/ui-react/syndesis/src/app/__mocks__/App.tsx
TypeScript error in app/ui-react/syndesis/src/app/__mocks__/App.tsx(1,49):
Could not find a declaration file for module '@syndesis/api'. 'app/ui-react/packages/api/dist/api.js' implicitly has an 'any' type.
  Try `npm install @types/syndesis__api` if it exists or add a new declaration (.d.ts) file containing `declare module '@syndesis/api';`  TS7016

  > 1 | import { ApiContext, ServerEventsContext } from '@syndesis/api';
      |                                                 ^
    2 | import * as React from 'react';
    3 | import { I18nextProvider } from 'react-i18next';
    4 | import i18n from '../../i18n';
```

And in addition to that adding `--jsx React.createElement` was required
to prevent errors like:

```
(rpt2 plugin) Error: app/ui-react/packages/apicurio-adapter/src/ApicurioAdapter.tsx(118,8): semantic error TS2304: Cannot find name 'h'.
Error: app/ui-react/packages/apicurio-adapter/src/ApicurioAdapter.tsx(118,8): semantic error TS2304: Cannot find name 'h'.
    at error (app/ui-react/node_modules/rollup/dist/shared/rollup.js:164:30)
    at throwPluginError (app/ui-react/node_modules/rollup/dist/shared/rollup.js:19161:12)
    at Object.error (app/ui-react/node_modules/rollup/dist/shared/rollup.js:19810:20)
    at Object.error (app/ui-react/node_modules/rollup/dist/shared/rollup.js:19337:38)
    at RollupContext.error (app/ui-react/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17237:30)
    at app/ui-react/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25033:23
    at arrayEach (app/ui-react/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:545:11)
    at Function.forEach (app/ui-react/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9397:14)
    at printDiagnostics (app/ui-react/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
    at Object.transform (app/ui-react/node_modules/microbundle/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29275:17)
```