fix(operator): test failure
I don't think this one is related to the changes I made. The test was
failing with:

```
--- FAIL: TestInstallAppNoCustomResource (0.00s)
    install_app_test.go:65:
        	Error Trace:	install_app_test.go:65
        	Error:      	Not equal:
        	            	expected: unstructured.Unstructured{Object:map[string]interface {}{"apiVersion":"syndesis.io/v1beta1", "kind":"Syndesis", "metadata":map[string]interface {}{"name":"app"}, "spec":map[string]interface {}{"addons":interface {}(nil)}, "status":map[string]interface {}{"apiVersion":"v1beta1"}}}
        	            	actual  : unstructured.Unstructured{Object:map[string]interface {}{"apiVersion":"syndesis.io/v1beta1", "kind":"Syndesis", "metadata":map[string]interface {}{"name":"app"}, "spec":map[string]interface {}{"addons":interface {}(nil)}}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 (unstructured.Unstructured) {
        	            	- Object: (map[string]interface {}) (len=5) {
        	            	+ Object: (map[string]interface {}) (len=4) {
        	            	   (string) (len=10) "apiVersion": (string) (len=19) "syndesis.io/v1beta1",
        	            	@@ -9,5 +9,2 @@
        	            	    (string) (len=6) "addons": (interface {}) <nil>
        	            	-  },
        	            	-  (string) (len=6) "status": (map[string]interface {}) (len=1) {
        	            	-   (string) (len=10) "apiVersion": (string) (len=7) "v1beta1"
        	            	   }
        	Test:       	TestInstallAppNoCustomResource
operator was installed successfully
```

(cherry picked from commit 946c681d83f715747d3959d3854944b1455abbe4)