Fixes CircleCI deployment error.
error: tag "latest" points to existing ImageStreamImage "ipaas-rest@sha256:2dba547c87f859dcd57e2e9ddf8fb38d4e1b03789f3d8c1aad9d11ae2f5a7cc8", it cannot be re-imported
(cherry picked from commit 55c2d29320a9f7e1180e8f653482d58626f71780)